apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: elasticsearch
  labels:
    app.kubernetes.io/name: filebeat
    app.kubernetes.io/instance: filebeat
    app.kubernetes.io/version: "7.10.1"
